service: serverless-starter

plugins:
  - serverless-webpack
  - serverless-offline

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: eu-west-3
  environment: ${file(env.yml):${self:provider.stage}}

functions:
  main:
    handler: handler.main
    events:
      - http:
          path: main
          method: get
